# Aggregate, Annotate, Normalize, and Feature Select

This notebook will run all these above operations on a single-cell file or well-aggregated file.

We will have the option to run or not

In [ ]:
path = r"path_to_environment"

In [2]:
import pandas as pd
import numpy as np
import pycytominer
import easygui as eg
import os
import sys
import gc
sys.path.append(path)
from scripts_notebooks_fossa.profiles import generate_profiles
%load_ext autoreload
%autoreload 2

# 0) Inputs

In [153]:
def stringToBool(s):
    return s.lower() == 'yes'

profile = eg.fileopenbox(msg="Choose a file with samples and their features", default=r"D:")
print('Filename', profile)

project_name = input('Provide the name of this project:')
print('Project name:', project_name)

metadata_question = input("If you need to annotate your dataset with an external file, write yes and press enter. If already annotated, answer no and press enter.")
metadata_answer = stringToBool(metadata_question)

if metadata_answer:
    platemap = eg.fileopenbox(msg="Choose a map (csv or txt file) with plates names and metadata filenames", default=r"G:")
    platemap_path = os.path.split(platemap)[0]
    print('Platemap file selected', platemap)
    
    # Read platemap using pandas (assuming it's either CSV or TXT)
    barcode_df = pd.read_csv(platemap)
else:
    barcode_df = None  # You can assign a default value or leave it as None, depending on your needs

cells_that_run = []
cells_that_run.append(project_name)

Filename G:\Meu Drive\Doutorado Thais\Github_Analysis\Dormant_NonDormant\SampleRetrival\Dormant_x_Nondormant_SingleCells.csv
Project name: ao
Platemap file selected G:\Meu Drive\Doutorado Thais\pHD_analysisfolder\workspace\metadata\platemaps\Dormant_x_normal\metadata\barcode_platemap.csv

In [154]:
barcode_df

      Assay_Plate_Barcode   Plate_Map_Name
0  240319_144243_Plate_1_  layout_day1.txt
1  240321_153415_Plate_1_  layout_day2.txt
2  240404_134523_Plate_1_  layout_day3.txt

In [155]:
gc.collect()

11

## 1) Import extracted features file (single cell or well-aggregated)

In [156]:
df = pd.read_csv(profile)
df.head()

,Metadata_Plate,Metadata_QCFlag,Metadata_QCFlag.1,Metadata_Site,Metadata_Well,Nuclei_ImageNumber,Nuclei_ObjectNumber,Nuclei_AreaShape_Area,Nuclei_AreaShape_BoundingBoxArea,Nuclei_AreaShape_BoundingBoxMaximum_X,...,Cells_Texture_Variance_AOPI_10_02_256,Cells_Texture_Variance_AOPI_10_03_256,Cells_Texture_Variance_AOPI_20_00_256,Cells_Texture_Variance_AOPI_20_01_256,Cells_Texture_Variance_AOPI_20_02_256,Cells_Texture_Variance_AOPI_20_03_256,Cells_Texture_Variance_AOPI_5_00_256,Cells_Texture_Variance_AOPI_5_01_256,Cells_Texture_Variance_AOPI_5_02_256,Cells_Texture_Variance_AOPI_5_03_256
0,240321_153415_Plate_1_,0,0,11,D10,3,1,2609,3534,150,...,41.960698,42.253443,42.380039,44.859571,43.866346,45.269071,40.532123,40.923713,41.380130,41.272143
1,240321_153415_Plate_1_,0,0,11,D10,3,2,1837,2255,513,...,214.205638,216.504315,207.841614,207.263831,222.108959,244.118014,206.658726,209.753136,207.986281,208.201253
2,240321_153415_Plate_1_,0,0,11,D10,3,3,2466,3190,82,...,53.725273,51.841565,64.554173,59.322037,51.237739,55.302862,63.215495,60.704996,60.425950,59.798456
3,240321_153415_Plate_1_,0,0,11,D10,3,4,2002,2700,498,...,212.610204,204.039853,188.735030,163.388927,209.904213,226.798017,212.344328,215.252342,219.046176,212.632572
4,240321_153415_Plate_1_,0,0,11,D10,3,5,1835,2322,558,...,340.827507,338.439665,358.311890,364.678780,372.306522,388.147483,322.325372,339.392508,327.577464,323.398845

### 1.a) Count number of cells in each well

In [157]:
object_count = (
                df.groupby(["Metadata_Plate", "Metadata_Well"])["Nuclei_Number_Object_Number"]
                .count()
                .reset_index()
                .rename({"Nuclei_Number_Object_Number": "Nuclei_cell_count"}, axis="columns")
            )

## 2) Generate profile

### 2A) Aggregate

- Run the next cell to list the metadata columns, and copy them to choose from which metadata information you'd like to join the rows on (strata)

- If using **already aggregated data by plates and wells**, skip to 2B.

In [158]:
pycytominer.cyto_utils.infer_cp_features(df, metadata=True)

['Metadata_Plate',
 'Metadata_QCFlag',
 'Metadata_QCFlag.1',
 'Metadata_Site',
 'Metadata_Well',
 'Metadata_Plate.1',
 'Metadata_QCFlag.2',
 'Metadata_QCFlag.1.1',
 'Metadata_Site.1',
 'Metadata_Well.1',
 'Metadata_Plate.2',
 'Metadata_QCFlag.3',
 'Metadata_QCFlag.1.2',
 'Metadata_Site.2',
 'Metadata_Well.2']

In [159]:
df1 = df

In [160]:
del df

In [161]:
gc.collect()

0

- As a default we are using **Metadata_Plate and Metadata_Well** to join the rows, using the **'median'** operation.

In [162]:
# Supondo que df1 seja seu DataFrame original
chunksize = 1000  # Ajuste baseado na memória do seu sistema
chunk_list = []

# Dividindo o DataFrame em pedaços
for chunk in range(0, len(df1), chunksize):
    chunk_df = df1.iloc[chunk:chunk+chunksize]
    
    # Agregando cada pedaço
    aggregated_chunk = pycytominer.aggregate(
        chunk_df, 
        strata=['Metadata_Plate', 'Metadata_Well'], 
        operation='median'
    )
    
    chunk_list.append(aggregated_chunk)

# Combinando todos os pedaços agregados em um único DataFrame
df2 = pd.concat(chunk_list)

# Mostrando as primeiras linhas do DataFrame original e do DataFrame agregado
print(df1.head())
print(df2.head())

           Metadata_Plate  Metadata_QCFlag  Metadata_QCFlag.1  Metadata_Site  \
0  240321_153415_Plate_1_                0                  0             11
1  240321_153415_Plate_1_                0                  0             11
2  240321_153415_Plate_1_                0                  0             11
3  240321_153415_Plate_1_                0                  0             11
4  240321_153415_Plate_1_                0                  0             11

  Metadata_Well  Nuclei_ImageNumber  Nuclei_ObjectNumber  \
0           D10                   3                    1
1           D10                   3                    2
2           D10                   3                    3
3           D10                   3                    4
4           D10                   3                    5

   Nuclei_AreaShape_Area  Nuclei_AreaShape_BoundingBoxArea  \
0                   2609                              3534
1                   1837                              2255
2                   2466                              3190
3                   2002                              2700
4                   1835                              2322

   Nuclei_AreaShape_BoundingBoxMaximum_X  ...  \
0                                    150  ...
1                                    513  ...
2                                     82  ...
3                                    498  ...
4                                    558  ...

   Cells_Texture_Variance_AOPI_10_02_256  \
0                              41.960698
1                             214.205638
2                              53.725273
3                             212.610204
4                             340.827507

   Cells_Texture_Variance_AOPI_10_03_256  \
0                              42.253443
1                             216.504315
2                              51.841565
3                             204.039853
4                             338.439665

   Cells_Texture_Variance_AOPI_20_00_256  \
0                              42.380039
1                             207.841614
2                              64.554173
3                             188.735030
4                             358.311890

   Cells_Texture_Variance_AOPI_20_01_256  \
0                              44.859571
1                             207.263831
2                              59.322037
3                             163.388927
4                             364.678780

   Cells_Texture_Variance_AOPI_20_02_256  \
0                              43.866346
1                             222.108959
2                              51.237739
3                             209.904213
4                             372.306522

   Cells_Texture_Variance_AOPI_20_03_256  \
0                              45.269071
1                             244.118014
2                              55.302862
3                             226.798017
4                             388.147483

   Cells_Texture_Variance_AOPI_5_00_256  Cells_Texture_Variance_AOPI_5_01_256  \
0                             40.532123                             40.923713
1                            206.658726                            209.753136
2                             63.215495                             60.704996
3                            212.344328                            215.252342
4                            322.325372                            339.392508

   Cells_Texture_Variance_AOPI_5_02_256  Cells_Texture_Variance_AOPI_5_03_256
0                             41.380130                             41.272143
1                            207.986281                            208.201253
2                             60.425950                             59.798456
3                            219.046176                            212.632572
4                            327.577464                            323.398845

[5 rows x 1830 columns]
           Metadata_Plate Metadata_Well  Nuclei_ImageNumber  \
0  240321_153415_Plate_1_           D10                 5.0
1  240321_153415_Plate_1_            D2                21.0
2  240321_153415_Plate_1_            D3                30.0
3  240321_153415_Plate_1_            D4                39.0
4  240321_153415_Plate_1_            D5                55.0

   Nuclei_ObjectNumber  Nuclei_AreaShape_Area  \
0                 15.0                 2362.0
1                 16.0                 2401.0
2                 12.0                 2561.0
3                 16.5                 2613.0
4                 12.0                 2475.0

   Nuclei_AreaShape_BoundingBoxArea  Nuclei_AreaShape_BoundingBoxMaximum_X  \
0                            3176.0                                  736.0
1                            3286.0                                  600.5
2                            3432.0                                  698.0
3                            3551.0                                  570.0
4                            3358.0                                  483.0

   Nuclei_AreaShape_BoundingBoxMaximum_Y  \
0                                  496.0
1                                  432.5
2                                  407.0
3                                  420.5
4                                  481.0

   Nuclei_AreaShape_BoundingBoxMinimum_X  \
0                                  671.0
1                                  549.5
2                                  639.0
3                                  506.0
4                                  423.0

   Nuclei_AreaShape_BoundingBoxMinimum_Y  ...  \
0                                  433.5  ...
1                                  377.0  ...
2                                  358.0  ...
3                                  360.0  ...
4                                  426.0  ...

   Cells_Texture_Variance_AOPI_10_02_256  \
0                             117.172863
1                              79.313272
2                             167.159046
3                             105.990296
4                             149.304994

   Cells_Texture_Variance_AOPI_10_03_256  \
0                             120.545778
1                              81.060638
2                             167.146434
3                             106.372240
4                             154.973374

   Cells_Texture_Variance_AOPI_20_00_256  \
0                             122.200612
1                              81.505940
2                             176.701743
3                             109.750079
4                             163.633431

   Cells_Texture_Variance_AOPI_20_01_256  \
0                             123.321553
1                              83.692298
2                             179.310752
3                             105.306401
4                             155.534723

   Cells_Texture_Variance_AOPI_20_02_256  \
0                             121.337172
1                              83.106544
2                             178.924247
3                             109.578703
4                             158.038845

   Cells_Texture_Variance_AOPI_20_03_256  \
0                             126.824477
1                              82.273788
2                             176.327158
3                             111.253055
4                             165.602048

   Cells_Texture_Variance_AOPI_5_00_256  Cells_Texture_Variance_AOPI_5_01_256  \
0                            116.869296                            116.762572
1                             79.014664                             76.812862
2                            165.319660                            166.585682
3                            104.171554                            102.921345
4                            148.172692                            145.988128

   Cells_Texture_Variance_AOPI_5_02_256  Cells_Texture_Variance_AOPI_5_03_256
0                            115.867556                            117.417512
1                             77.376023                             77.292308
2                            165.616544                            164.865590
3                            103.801638                            103.977219
4                            148.552698                            149.571166

[5 rows x 1817 columns]

### 2B) Annotate

In [163]:
df = df2

In [164]:
del df1

In [165]:
del df2

In [166]:
gc.collect()

0

- Run the following to generate a plate list based on Metadata_Plate column.

In [167]:
plate_list = df['Metadata_Plate'].unique().tolist()

In [168]:
print(plate_list)

['240321_153415_Plate_1_', '240404_134523_Plate_1_']

In [169]:
# Supondo que df seja seu DataFrame original
df.drop_duplicates(subset=['Metadata_Plate', 'Metadata_Well'], keep='first', inplace=True)

# Exibindo as primeiras linhas do DataFrame após remover duplicados
print(df.head())

           Metadata_Plate Metadata_Well  Nuclei_ImageNumber  \
0  240321_153415_Plate_1_           D10                 5.0
1  240321_153415_Plate_1_            D2                21.0
2  240321_153415_Plate_1_            D3                30.0
3  240321_153415_Plate_1_            D4                39.0
4  240321_153415_Plate_1_            D5                55.0

   Nuclei_ObjectNumber  Nuclei_AreaShape_Area  \
0                 15.0                 2362.0
1                 16.0                 2401.0
2                 12.0                 2561.0
3                 16.5                 2613.0
4                 12.0                 2475.0

   Nuclei_AreaShape_BoundingBoxArea  Nuclei_AreaShape_BoundingBoxMaximum_X  \
0                            3176.0                                  736.0
1                            3286.0                                  600.5
2                            3432.0                                  698.0
3                            3551.0                                  570.0
4                            3358.0                                  483.0

   Nuclei_AreaShape_BoundingBoxMaximum_Y  \
0                                  496.0
1                                  432.5
2                                  407.0
3                                  420.5
4                                  481.0

   Nuclei_AreaShape_BoundingBoxMinimum_X  \
0                                  671.0
1                                  549.5
2                                  639.0
3                                  506.0
4                                  423.0

   Nuclei_AreaShape_BoundingBoxMinimum_Y  ...  \
0                                  433.5  ...
1                                  377.0  ...
2                                  358.0  ...
3                                  360.0  ...
4                                  426.0  ...

   Cells_Texture_Variance_AOPI_10_02_256  \
0                             117.172863
1                              79.313272
2                             167.159046
3                             105.990296
4                             149.304994

   Cells_Texture_Variance_AOPI_10_03_256  \
0                             120.545778
1                              81.060638
2                             167.146434
3                             106.372240
4                             154.973374

   Cells_Texture_Variance_AOPI_20_00_256  \
0                             122.200612
1                              81.505940
2                             176.701743
3                             109.750079
4                             163.633431

   Cells_Texture_Variance_AOPI_20_01_256  \
0                             123.321553
1                              83.692298
2                             179.310752
3                             105.306401
4                             155.534723

   Cells_Texture_Variance_AOPI_20_02_256  \
0                             121.337172
1                              83.106544
2                             178.924247
3                             109.578703
4                             158.038845

   Cells_Texture_Variance_AOPI_20_03_256  \
0                             126.824477
1                              82.273788
2                             176.327158
3                             111.253055
4                             165.602048

   Cells_Texture_Variance_AOPI_5_00_256  Cells_Texture_Variance_AOPI_5_01_256  \
0                            116.869296                            116.762572
1                             79.014664                             76.812862
2                            165.319660                            166.585682
3                            104.171554                            102.921345
4                            148.172692                            145.988128

   Cells_Texture_Variance_AOPI_5_02_256  Cells_Texture_Variance_AOPI_5_03_256
0                            115.867556                            117.417512
1                             77.376023                             77.292308
2                            165.616544                            164.865590
3                            103.801638                            103.977219
4                            148.552698                            149.571166

[5 rows x 1817 columns]

- All metadata must be organized such:
    ```
    |- metadata 
    |   |   |- <barcode_platemap.csv> 
    |   |- platemap
    |   |   |- <platemap_1.csv>
    |   |   |- <platemap_2.csv>
    ```

- Run the next cell to annotate the profiles.

In [170]:
df_temp_list = []
for pl in plate_list:
    df_plate = df.loc[df['Metadata_Plate'] == pl]
    #deal with metadata information
    barcode_map = barcode_df[barcode_df['Assay_Plate_Barcode'] == pl]
    index_map = barcode_map.index[0]
    metadata_filename = barcode_df['Plate_Map_Name'][index_map]
    metadata = pd.read_csv(platemap_path + r'/platemap/' + metadata_filename)
    #annotate
    df_temp = pycytominer.annotate(profiles = df_plate, platemap = metadata, join_on =  ["Metadata_well_position", "Metadata_Well"])
    df_temp_list.append(df_temp)
    print('Shape of each plate ', df_temp.shape)
df = pd.concat(df_temp_list, axis=0)

Shape of each plate  (7, 1822)
Shape of each plate  (48, 1822)

In [171]:
df

,Metadata_plate_map_name,Metadata_cell,Metadata_compound,Metadata_concentration_uM,Metadata_control_type,Metadata_Plate,Metadata_Well,Nuclei_ImageNumber,Nuclei_ObjectNumber,Nuclei_AreaShape_Area,...,Cells_Texture_Variance_AOPI_10_02_256,Cells_Texture_Variance_AOPI_10_03_256,Cells_Texture_Variance_AOPI_20_00_256,Cells_Texture_Variance_AOPI_20_01_256,Cells_Texture_Variance_AOPI_20_02_256,Cells_Texture_Variance_AOPI_20_03_256,Cells_Texture_Variance_AOPI_5_00_256,Cells_Texture_Variance_AOPI_5_01_256,Cells_Texture_Variance_AOPI_5_02_256,Cells_Texture_Variance_AOPI_5_03_256
0,layout_day2,MCF7,CoCl2,300,trt,240321_153415_Plate_1_,D2,21.0,16.0,2401.0,...,79.313272,81.060638,81.505940,83.692298,83.106544,82.273788,79.014664,76.812862,77.376023,77.292308
1,layout_day2,MCF7,CoCl2,300,trt,240321_153415_Plate_1_,D3,30.0,12.0,2561.0,...,167.159046,167.146434,176.701743,179.310752,178.924247,176.327158,165.319660,166.585682,165.616544,164.865590
2,layout_day2,MCF7,CoCl2,300,trt,240321_153415_Plate_1_,D4,39.0,16.5,2613.0,...,105.990296,106.372240,109.750079,105.306401,109.578703,111.253055,104.171554,102.921345,103.801638,103.977219
3,layout_day2,MCF7,CoCl2,300,trt,240321_153415_Plate_1_,D5,55.0,12.0,2475.0,...,149.304994,154.973374,163.633431,155.534723,158.038845,165.602048,148.172692,145.988128,148.552698,149.571166
4,layout_day2,MCF7,Non-treated,0,negcon,240321_153415_Plate_1_,D8,82.0,13.5,2547.5,...,124.827431,128.086831,130.741632,126.910012,132.165969,145.816317,123.932335,125.071066,122.922661,124.266384
5,layout_day2,MCF7,Non-treated,0,negcon,240321_153415_Plate_1_,D9,90.0,12.0,2255.0,...,126.293607,126.716892,126.199596,131.611286,127.413918,132.868554,121.934521,123.814786,122.101645,125.197131
6,layout_day2,MCF7,Non-treated,0,negcon,240321_153415_Plate_1_,D10,5.0,15.0,2362.0,...,117.172863,120.545778,122.200612,123.321553,121.337172,126.824477,116.869296,116.762572,115.867556,117.417512
0,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,B2,28.0,24.5,2472.0,...,79.886378,81.126300,81.974851,84.407436,82.191830,84.994218,78.331306,79.250831,79.113506,80.084876
1,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,B3,43.0,24.0,2501.0,...,107.965187,110.179120,112.727345,115.447942,114.363372,114.737525,108.003177,108.132711,106.388520,106.788609
2,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,B4,50.0,25.0,2604.0,...,165.661592,166.878070,173.801704,177.730442,168.535731,170.314936,162.627386,164.225957,161.790491,162.922025
3,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,B7,79.0,4.5,2364.5,...,323.022646,323.197310,346.876653,344.495070,343.019245,358.448606,317.325987,322.334228,316.695373,314.476087
4,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,B8,91.0,13.0,2586.0,...,272.599097,284.260665,283.041431,302.881055,278.444984,281.985586,263.127932,264.198800,263.960186,268.144671
5,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,B9,103.0,12.0,2526.5,...,232.752021,236.375760,236.653939,248.273496,239.043422,253.281412,232.768009,229.604956,231.874363,233.087621
6,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,B10,8.0,14.0,2512.0,...,262.900887,266.234944,280.395706,298.172541,281.021900,289.136469,255.693601,258.393135,256.608620,259.234365
7,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,B11,17.0,9.0,2477.0,...,249.818194,232.712645,245.234972,248.718400,257.310093,249.869219,236.293876,242.065818,241.703839,241.475913
8,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,C2,133.0,22.5,2051.5,...,114.537292,117.543242,116.117861,117.668486,113.689386,114.061145,114.631380,112.217821,111.049482,110.879531
9,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,C3,153.0,22.0,2555.0,...,189.897519,195.950888,195.139389,199.847084,201.044644,199.855080,187.765502,188.181687,188.714343,192.286749
10,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,C4,167.0,24.0,2807.0,...,184.678609,191.561404,195.193751,194.842326,197.838500,205.977530,182.437871,183.102019,180.343276,182.358354
11,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,C7,182.0,11.5,2445.5,...,211.172979,215.398226,225.738255,230.994385,222.862498,219.814942,207.002878,208.436532,207.316974,209.437456
12,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,C8,200.0,10.0,2475.0,...,276.134331,283.709518,286.629605,301.608271,297.808315,298.797759,266.585901,271.181217,268.583288,273.788263
13,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,C9,211.0,9.0,2508.0,...,233.276492,241.741676,237.761748,247.044419,244.298933,238.893778,224.048040,226.564974,224.492190,231.921094
14,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,C10,114.0,10.0,2594.5,...,228.350318,234.771490,237.766458,254.462080,246.432138,248.795311,229.461001,228.032197,225.115426,226.450933
15,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,C11,126.0,11.0,2451.0,...,218.990475,227.167730,233.409090,236.084921,234.275800,244.819220,211.503266,214.946313,212.371189,213.322456
16,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,D2,245.0,28.0,2583.0,...,159.608576,162.629370,164.215825,168.450951,162.922651,170.334967,156.874112,158.280991,157.614922,156.651102
17,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,D3,260.0,24.0,2632.0,...,143.209290,144.976123,148.735569,150.564950,150.871094,156.230099,141.970299,142.967891,140.901181,142.551030
18,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,D4,274.0,25.0,2647.0,...,233.837129,237.333776,250.675991,249.416510,246.161146,260.712366,235.345071,236.514737,233.828032,232.737974
19,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,D7,295.0,9.0,2632.5,...,283.520318,295.190049,295.898319,316.456610,307.434575,303.248521,274.797260,276.973068,274.009409,276.695252
20,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,D8,307.0,10.0,2495.0,...,285.430922,294.174832,302.175495,323.610139,306.298390,323.720302,272.149009,277.436774,275.047269,278.642321
21,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,D9,313.0,5.0,2391.0,...,242.898967,212.199237,244.597256,288.980155,231.903291,252.225126,258.095983,268.913294,253.572275,234.732799
22,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,D10,222.0,7.0,2689.0,...,144.743378,149.263900,157.921560,156.586177,152.408698,152.385054,144.256559,143.814804,142.882623,144.362939
23,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,D11,235.0,11.0,2591.0,...,270.989585,277.081631,286.164564,294.560903,286.889754,299.935003,263.740176,269.093862,261.112161,261.644686
24,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,E2,356.0,32.5,2465.0,...,157.922696,160.478706,164.870180,171.111306,163.996553,164.194454,156.286772,157.476236,156.367603,157.389162
25,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,E3,362.0,25.0,2619.0,...,165.454323,169.209497,176.104873,179.498527,169.618714,175.504397,167.153618,165.041392,164.011054,166.376064
26,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,E4,378.0,28.0,2627.0,...,170.920564,174.560333,176.021090,182.135124,176.896738,181.165945,169.891536,171.330805,168.860854,168.844846
27,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,E7,403.0,9.0,2470.0,...,357.270595,365.091231,355.746748,380.271325,360.622805,370.154645,335.475785,339.478793,340.816113,351.790637
28,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,E8,409.0,7.0,2415.0,...,293.501577,301.254011,297.564376,331.053862,310.975661,322.288080,295.556059,289.754672,294.287124,298.193694
29,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,E9,427.0,10.0,2596.0,...,312.970865,326.071348,331.470135,342.023611,342.939770,353.384023,300.213999,302.697746,300.051554,306.950875
30,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,E10,332.0,11.0,2505.0,...,206.797997,216.423583,229.443254,252.581767,233.602632,241.140085,202.860671,202.383102,199.651586,205.039429
31,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,E11,343.0,10.0,2548.0,...,309.981366,316.164279,317.957884,326.876234,323.154714,335.290340,298.757205,301.545703,298.846115,303.657211
32,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,F2,463.0,30.0,2502.5,...,161.948288,167.434729,172.331937,175.133421,171.499956,171.745041,161.924118,162.656915,160.544255,162.119960
33,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,F3,473.0,23.0,2645.0,...,187.326445,190.206353,194.317990,193.435502,192.492184,197.944596,186.850703,186.879346,186.194566,186.518622
34,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,F4,487.0,28.0,2616.0,...,130.543253,129.138893,131.561808,127.915403,130.318460,135.178597,129.966963,129.691479,129.680160,129.924197
35,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,F7,509.0,10.0,2612.0,...,415.519087,428.300840,448.491733,461.446516,454.318519,472.388462,403.417323,419.282375,415.314069,404.110238
36,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,F8,524.0,13.0,2519.5,...,178.772062,184.537825,199.686187,194.541757,184.772650,196.828912,184.128980,176.363804,175.318338,180.365625
37,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,F9,536.0,8.0,2719.5,...,329.481412,337.130991,359.239568,372.405647,338.029081,377.693046,314.543580,322.095376,318.964122,321.858266
38,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,F10,439.0,10.0,2658.0,...,312.257678,324.534849,335.843628,352.545248,346.552372,355.193392,294.897968,301.834578,295.954765,300.882027
39,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,F11,451.0,9.0,2584.5,...,349.273574,365.229812,366.354662,386.801636,381.392289,414.731891,335.201656,343.725778,335.216116,340.272935
40,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,G2,573.0,25.0,2546.0,...,161.703687,162.266286,165.173850,165.602374,168.003009,166.569507,164.528423,165.827367,162.307727,164.840232
41,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,G3,577.0,18.0,2582.5,...,262.663875,262.384335,262.560938,257.923965,264.660801,257.247599,264.306462,265.554754,264.871120,265.403731
42,layout_day3,MCF7,CoCl2,300,trt,240404_134523_Plate_1_,G4,596.0,26.5,2682.0,...,194.900008,196.705077,200.138510,205.441916,201.137262,203.176006,193.728699,192.111462,193.239805,194.130651
43,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,G7,618.0,8.5,2571.0,...,441.149287,463.259923,441.001966,488.229585,480.814984,479.781553,424.381717,445.408767,436.130867,433.302451
44,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,G8,631.0,9.0,2629.0,...,439.642194,449.129680,481.631786,504.528270,482.131971,469.312976,414.196650,423.875953,416.295001,424.591999
45,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,G9,644.0,9.0,2541.5,...,400.016842,405.350586,406.192813,442.568905,437.789626,430.179700,378.593094,382.656222,380.151104,388.655001
46,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,G10,546.0,9.0,2694.0,...,369.612620,381.120135,400.838169,405.423802,397.661348,411.600197,354.272910,358.918338,354.790195,358.749143
47,layout_day3,MCF7,Non-treated,0,negcon,240404_134523_Plate_1_,G11,558.0,9.0,2610.0,...,379.103765,386.367887,410.313719,418.841676,407.641304,423.637404,365.124970,365.328516,363.828344,373.699225

In [172]:
df = object_count.merge(df, on=['Metadata_Plate','Metadata_Well'])

### 2C) Normalize

- Normalize the dataset, per-plate basis, to **samples = all** or **samples = negcon**.
- CHOOSE one or the other below.

#### Normalize TO NEGCON => run next cell

In [173]:
df_temp_list = []
for pl in plate_list:
    df_temp = df.loc[df['Metadata_Plate'] == pl]
    print(df_temp.shape)
    df_norm_temp = pycytominer.normalize(df_temp, method = 'mad_robustize', mad_robustize_epsilon = 0, samples = "Metadata_control_type	 == 'negcon'") 
    df_temp_list.append(df_norm_temp)
df_norm2 = pd.concat(df_temp_list, axis=0)
cells_that_run.append('normalized_negcon')

(7, 1823)
(48, 1823)

c:\Users\Lab\miniconda3\envs\bioimage_scripts\lib\site-packages\scipy\stats\_stats_py.py:2894: RuntimeWarning: invalid value encountered in subtract
  mad = np.median(np.abs(x - med))
c:\Users\Lab\miniconda3\envs\bioimage_scripts\lib\site-packages\scipy\stats\_stats_py.py:2894: RuntimeWarning: invalid value encountered in subtract
  mad = np.median(np.abs(x - med))

In [174]:
df_norm2

,Metadata_Plate,Metadata_Well,Metadata_plate_map_name,Metadata_cell,Metadata_compound,Metadata_concentration_uM,Metadata_control_type,Nuclei_cell_count,Nuclei_ImageNumber,Nuclei_ObjectNumber,...,Cells_Texture_Variance_AOPI_10_02_256,Cells_Texture_Variance_AOPI_10_03_256,Cells_Texture_Variance_AOPI_20_00_256,Cells_Texture_Variance_AOPI_20_01_256,Cells_Texture_Variance_AOPI_20_02_256,Cells_Texture_Variance_AOPI_20_03_256,Cells_Texture_Variance_AOPI_5_00_256,Cells_Texture_Variance_AOPI_5_01_256,Cells_Texture_Variance_AOPI_5_02_256,Cells_Texture_Variance_AOPI_5_03_256
0,240321_153415_Plate_1_,D10,layout_day2,MCF7,Non-treated,0,negcon,0.000000,-6.491974,0.674491,...,-3.521361,-3.038353,-0.674491,-0.674491,-0.862514,-0.674491,-1.710093,-3.786299,-5.121499,-4.963221
1,240321_153415_Plate_1_,D2,layout_day2,MCF7,CoCl2,300,trt,0.578135,-5.142992,1.124151,...,-20.938057,-22.478892,-7.538279,-8.123250,-6.288845,-5.646139,-14.490365,-25.235105,-36.743500,-34.041037
2,240321_153415_Plate_1_,D3,layout_day2,MCF7,CoCl2,300,trt,-2.408896,-4.384190,-0.674491,...,19.473980,19.905516,8.517971,9.849302,7.311209,4.849777,14.647451,22.963487,35.748854,29.421314
3,240321_153415_Plate_1_,D4,layout_day2,MCF7,CoCl2,300,trt,15.416932,-3.625388,1.348982,...,-8.665721,-10.016705,-2.774467,-4.060639,-2.531473,-2.412189,-5.997035,-11.217587,-15.034029,-14.703093
4,240321_153415_Plate_1_,D5,layout_day2,MCF7,CoCl2,300,trt,4.336012,-2.276406,-0.674491,...,11.260510,13.912101,6.313798,5.380333,4.346803,3.652905,8.858386,11.904760,21.730369,18.337795
5,240321_153415_Plate_1_,D8,layout_day2,MCF7,Non-treated,0,negcon,-6.937619,0.000000,0.000000,...,0.000000,0.674491,0.766085,0.000000,0.674491,1.444910,0.674491,0.674491,0.674491,0.000000
6,240321_153415_Plate_1_,D9,layout_day2,MCF7,Non-treated,0,negcon,0.674491,0.674491,-0.674491,...,0.674491,0.000000,0.000000,0.883657,0.000000,0.000000,0.000000,0.000000,0.000000,0.674491
7,240404_134523_Plate_1_,B10,layout_day3,MCF7,Non-treated,0,negcon,-1.623774,-1.297415,6.070417,...,-0.282774,-0.314858,-0.186774,-0.222835,-0.283442,-0.251268,-0.272967,-0.262231,-0.257578,-0.275302
8,240404_134523_Plate_1_,B11,layout_day3,MCF7,Non-treated,0,negcon,-0.624528,-1.260287,-0.674491,...,-0.454246,-0.685884,-0.588784,-0.726937,-0.543493,-0.668782,-0.570809,-0.489828,-0.471819,-0.540509
9,240404_134523_Plate_1_,B2,layout_day3,MCF7,CoCl2,300,trt,10.891777,-1.214908,20.234723,...,-2.681498,-2.363649,-2.455418,-2.401814,-2.464043,-2.421833,-2.995991,-2.759419,-2.808894,-2.950741
10,240404_134523_Plate_1_,B3,layout_day3,MCF7,CoCl2,300,trt,10.467097,-1.153029,19.560232,...,-2.313477,-2.042091,-2.103810,-2.085408,-2.111213,-2.105584,-2.540442,-2.356815,-2.416842,-2.551944
11,240404_134523_Plate_1_,B4,layout_day3,MCF7,CoCl2,300,trt,8.093889,-1.124151,20.909214,...,-1.557265,-1.414544,-1.405516,-1.450542,-1.517096,-1.514651,-1.701803,-1.574892,-1.620494,-1.713641
12,240404_134523_Plate_1_,B7,layout_day3,MCF7,Non-treated,0,negcon,-3.297510,-1.004517,-6.744908,...,0.505226,0.315604,0.573336,0.249346,0.396493,0.485701,0.673268,0.629089,0.606109,0.549684
13,240404_134523_Plate_1_,B8,layout_day3,MCF7,Non-treated,0,negcon,-2.373208,-0.955013,4.721435,...,-0.155663,-0.115349,-0.156524,-0.174839,-0.311703,-0.327301,-0.158829,-0.181301,-0.151907,-0.142234
14,240404_134523_Plate_1_,B9,layout_day3,MCF7,Non-treated,0,negcon,0.449661,-0.905509,3.372454,...,-0.677928,-0.645341,-0.686895,-0.731473,-0.743826,-0.632501,-0.624941,-0.663529,-0.613108,-0.665780
15,240404_134523_Plate_1_,C10,layout_day3,MCF7,Non-treated,0,negcon,-1.049208,-0.860130,0.674491,...,-0.735620,-0.663097,-0.674175,-0.668390,-0.662793,-0.680200,-0.675713,-0.685453,-0.710261,-0.764893
16,240404_134523_Plate_1_,C11,layout_day3,MCF7,Non-treated,0,negcon,0.999246,-0.810627,2.023472,...,-0.858297,-0.747256,-0.723995,-0.855715,-0.796114,-0.722476,-0.951417,-0.867866,-0.893447,-0.960955
17,240404_134523_Plate_1_,C2,layout_day3,MCF7,CoCl2,300,trt,5.645737,-0.781749,17.536760,...,-2.227338,-1.960585,-2.065044,-2.062773,-2.118604,-2.112776,-2.438680,-2.299869,-2.349846,-2.490850
18,240404_134523_Plate_1_,C3,layout_day3,MCF7,CoCl2,300,trt,3.822114,-0.699243,16.862269,...,-1.239611,-1.092765,-1.161552,-1.225099,-1.160565,-1.200562,-1.315860,-1.240957,-1.233491,-1.275105
19,240404_134523_Plate_1_,C4,layout_day3,MCF7,CoCl2,300,trt,1.124151,-0.641488,19.560232,...,-1.308014,-1.141348,-1.160930,-1.276114,-1.195727,-1.135465,-1.397654,-1.311766,-1.353816,-1.423377
20,240404_134523_Plate_1_,C7,layout_day3,MCF7,Non-treated,0,negcon,-0.749434,-0.579608,2.697963,...,-0.960759,-0.877521,-0.811700,-0.907604,-0.921285,-0.988337,-1.020511,-0.958610,-0.966096,-1.018975
21,240404_134523_Plate_1_,C8,layout_day3,MCF7,Non-treated,0,negcon,0.674491,-0.505352,0.674491,...,-0.109327,-0.121449,-0.115498,-0.187813,-0.099342,-0.148543,-0.105739,-0.083969,-0.085454,-0.057952
22,240404_134523_Plate_1_,C9,layout_day3,MCF7,Non-treated,0,negcon,-0.499623,-0.459974,-0.674491,...,-0.671054,-0.585951,-0.674229,-0.744001,-0.686188,-0.785479,-0.758818,-0.705905,-0.719220,-0.683201
23,240404_134523_Plate_1_,D10,layout_day3,MCF7,Non-treated,0,negcon,-1.623774,-0.414595,-3.372454,...,-1.831434,-1.609499,-1.587082,-1.666072,-1.693963,-1.705293,-1.983848,-1.859417,-1.892276,-1.990805
24,240404_134523_Plate_1_,D11,layout_day3,MCF7,Non-treated,0,negcon,1.473887,-0.360966,2.023472,...,-0.176758,-0.194807,-0.120815,-0.259649,-0.219088,-0.136451,-0.149429,-0.113066,-0.192844,-0.239306
25,240404_134523_Plate_1_,D2,layout_day3,MCF7,CoCl2,300,trt,4.496605,-0.319713,24.956158,...,-1.636600,-1.461569,-1.515116,-1.545131,-1.578655,-1.514438,-1.790132,-1.657763,-1.680514,-1.807292
26,240404_134523_Plate_1_,D3,layout_day3,MCF7,CoCl2,300,trt,3.422416,-0.257833,19.560232,...,-1.851541,-1.656956,-1.692110,-1.727449,-1.710826,-1.664410,-2.018949,-1.871223,-1.920757,-2.017864
27,240404_134523_Plate_1_,D4,layout_day3,MCF7,CoCl2,300,trt,3.597284,-0.200078,20.909214,...,-0.663706,-0.634738,-0.526574,-0.719821,-0.665765,-0.553491,-0.585376,-0.567209,-0.585026,-0.671002
28,240404_134523_Plate_1_,D7,layout_day3,MCF7,Non-treated,0,negcon,-0.349736,-0.113446,-0.674491,...,-0.012521,0.005618,-0.009524,-0.036459,0.006230,-0.101220,0.020329,-0.003232,-0.007459,-0.014539
29,240404_134523_Plate_1_,D8,layout_day3,MCF7,Non-treated,0,negcon,-0.449661,-0.063943,0.674491,...,0.012521,-0.005618,0.062246,0.036459,-0.006230,0.116448,-0.020329,0.003232,0.007459,0.014539
30,240404_134523_Plate_1_,D9,layout_day3,MCF7,Non-treated,0,negcon,0.599547,-0.039191,-6.070417,...,-0.544934,-0.912928,-0.596075,-0.316536,-0.822133,-0.643732,-0.236084,-0.115583,-0.301223,-0.641211
31,240404_134523_Plate_1_,E10,layout_day3,MCF7,Non-treated,0,negcon,0.724453,0.039191,2.023472,...,-1.018100,-0.866173,-0.769338,-0.687557,-0.803496,-0.761595,-1.084105,-1.042993,-1.076279,-1.084655
32,240404_134523_Plate_1_,E11,layout_day3,MCF7,Non-treated,0,negcon,0.374717,0.084569,0.674491,...,0.334297,0.237762,0.242694,0.069752,0.178636,0.239468,0.388184,0.339303,0.349544,0.388114
33,240404_134523_Plate_1_,E2,layout_day3,MCF7,CoCl2,300,trt,7.544304,0.138198,31.026575,...,-1.658696,-1.485373,-1.507635,-1.518013,-1.566877,-1.579728,-1.799149,-1.668981,-1.698443,-1.796270
34,240404_134523_Plate_1_,E3,layout_day3,MCF7,CoCl2,300,trt,5.370945,0.162950,20.909214,...,-1.559981,-1.388740,-1.379183,-1.432519,-1.505218,-1.459474,-1.632312,-1.563525,-1.588576,-1.662058
35,240404_134523_Plate_1_,E4,layout_day3,MCF7,CoCl2,300,trt,5.920530,0.228956,24.956158,...,-1.488337,-1.329517,-1.380141,-1.405643,-1.425399,-1.399277,-1.590277,-1.475853,-1.518865,-1.625189
36,240404_134523_Plate_1_,E7,layout_day3,MCF7,Non-treated,0,negcon,-0.674491,0.332089,-0.674491,...,0.954105,0.779288,0.674753,0.614026,0.589554,0.610167,0.951920,0.868079,0.952821,1.106944
37,240404_134523_Plate_1_,E8,layout_day3,MCF7,Non-treated,0,negcon,0.499623,0.356841,-3.372454,...,0.118301,0.072734,0.009524,0.112336,0.045066,0.101220,0.339037,0.174940,0.284013,0.306521
38,240404_134523_Plate_1_,E9,layout_day3,MCF7,Non-treated,0,negcon,1.074189,0.431097,0.674491,...,0.373480,0.347414,0.397186,0.224154,0.395622,0.431851,0.410550,0.355362,0.366871,0.437302
39,240404_134523_Plate_1_,F10,layout_day3,MCF7,Non-treated,0,negcon,-0.349736,0.480600,0.674491,...,0.364132,0.330408,0.447190,0.331404,0.435242,0.451090,0.328933,0.343330,0.307984,0.346669
40,240404_134523_Plate_1_,F11,layout_day3,MCF7,Non-treated,0,negcon,-0.249811,0.530104,-0.674491,...,0.849290,0.780821,0.796038,0.680591,0.817336,1.084139,0.947711,0.927280,0.872326,0.934938
41,240404_134523_Plate_1_,F2,layout_day3,MCF7,CoCl2,300,trt,8.593512,0.579608,27.654121,...,-1.605934,-1.408383,-1.422321,-1.477014,-1.484586,-1.499446,-1.712600,-1.596764,-1.638408,-1.725619
42,240404_134523_Plate_1_,F3,layout_day3,MCF7,CoCl2,300,trt,5.271020,0.620862,18.211251,...,-1.273309,-1.156346,-1.170943,-1.290455,-1.254361,-1.220876,-1.329905,-1.259111,-1.269710,-1.361247
43,240404_134523_Plate_1_,F4,layout_day3,MCF7,CoCl2,300,trt,1.873585,0.678616,24.956158,...,-2.017552,-1.832243,-1.888466,-1.958323,-1.936231,-1.888242,-2.203235,-2.056292,-2.082048,-2.206435
44,240404_134523_Plate_1_,F7,layout_day3,MCF7,Non-treated,0,negcon,1.473887,0.769373,0.674491,...,1.717553,1.478894,1.735152,1.441472,1.617130,1.697179,1.995019,1.980516,2.023655,1.888291
45,240404_134523_Plate_1_,F8,layout_day3,MCF7,Non-treated,0,negcon,0.049962,0.831253,4.721435,...,-1.385429,-1.219085,-1.109566,-1.279178,-1.339023,-1.232739,-1.371691,-1.405694,-1.426045,-1.453137
46,240404_134523_Plate_1_,F9,layout_day3,MCF7,Non-treated,0,negcon,0.000000,0.880757,-2.023472,...,0.589879,0.469822,0.714688,0.533848,0.341765,0.690320,0.630550,0.625759,0.638720,0.659931
47,240404_134523_Plate_1_,G10,layout_day3,MCF7,Non-treated,0,negcon,0.824378,0.922010,-0.674491,...,1.115869,0.956696,1.190305,0.870413,0.995762,1.050841,1.240510,1.139060,1.153684,1.210863
48,240404_134523_Plate_1_,G11,layout_day3,MCF7,Non-treated,0,negcon,0.574566,0.971514,-0.674491,...,1.240267,1.014779,1.298644,1.007186,1.105214,1.178828,1.407121,1.228416,1.283599,1.434130
49,240404_134523_Plate_1_,G2,layout_day3,MCF7,CoCl2,300,trt,2.373208,1.033394,20.909214,...,-1.609140,-1.465588,-1.504163,-1.574167,-1.522938,-1.554475,-1.672616,-1.552569,-1.613060,-1.684995
50,240404_134523_Plate_1_,G3,layout_day3,MCF7,CoCl2,300,trt,1.948529,1.049895,11.466343,...,-0.285881,-0.357477,-0.390687,-0.633102,-0.462876,-0.590330,-0.140735,-0.162400,-0.138813,-0.183168
51,240404_134523_Plate_1_,G4,layout_day3,MCF7,CoCl2,300,trt,6.744908,1.128277,22.932686,...,-1.174044,-1.084418,-1.104394,-1.168069,-1.159549,-1.165252,-1.224308,-1.186177,-1.168442,-1.247568
52,240404_134523_Plate_1_,G7,layout_day3,MCF7,Non-treated,0,negcon,-0.999246,1.219034,-1.348982,...,2.053481,1.865823,1.649518,1.714480,1.907721,1.775787,2.316883,2.344710,2.322875,2.324251
53,240404_134523_Plate_1_,G8,layout_day3,MCF7,Non-treated,0,negcon,0.000000,1.272663,-0.674491,...,2.033728,1.709429,2.114059,1.880618,1.922165,1.664479,2.160513,2.044549,2.037755,2.194168
54,240404_134523_Plate_1_,G9,layout_day3,MCF7,Non-treated,0,negcon,0.899321,1.326292,-0.674491,...,1.514369,1.224880,1.251528,1.249046,1.435855,1.248390,1.613895,1.469959,1.518222,1.657481

### 2D) Feature selection

In [175]:
#porque o codigo abaixo estava dando erro de versao
np.bool = bool

In [176]:
df_selected = pycytominer.feature_select(df_norm2, operation = ['correlation_threshold', 'variance_threshold', 'drop_na_columns','drop_outliers'], outlier_cutoff = 500) 
print('Number of columns removed:', df_norm2.shape[1] - df_selected.shape[1])
print('Percentage of columns removed:',100 - ((df_selected.shape[1]*100)/df_norm2.shape[1]))
cells_that_run.append('feature_select')

Number of columns removed: 1400
Percentage of columns removed: 76.79648930334614

In [177]:
print(df_selected.columns.tolist())

['Metadata_Plate', 'Metadata_Well', 'Metadata_plate_map_name', 'Metadata_cell', 'Metadata_compound', 'Metadata_concentration_uM', 'Metadata_control_type', 'Nuclei_cell_count', 'Nuclei_AreaShape_CentralMoment_0_1', 'Nuclei_AreaShape_CentralMoment_1_0', 'Nuclei_AreaShape_CentralMoment_1_2', 'Nuclei_AreaShape_CentralMoment_2_1', 'Nuclei_AreaShape_EquivalentDiameter', 'Nuclei_AreaShape_Extent', 'Nuclei_AreaShape_FormFactor', 'Nuclei_AreaShape_HuMoment_2', 'Nuclei_AreaShape_HuMoment_4', 'Nuclei_AreaShape_HuMoment_5', 'Nuclei_AreaShape_HuMoment_6', 'Nuclei_AreaShape_InertiaTensor_0_0', 'Nuclei_AreaShape_InertiaTensor_1_0', 'Nuclei_AreaShape_InertiaTensor_1_1', 'Nuclei_AreaShape_MajorAxisLength', 'Nuclei_AreaShape_MaximumRadius', 'Nuclei_AreaShape_MedianRadius', 'Nuclei_AreaShape_NormalizedMoment_0_2', 'Nuclei_AreaShape_NormalizedMoment_0_3', 'Nuclei_AreaShape_NormalizedMoment_2_0', 'Nuclei_AreaShape_NormalizedMoment_2_2', 'Nuclei_AreaShape_NormalizedMoment_2_3', 'Nuclei_AreaShape_NormalizedMoment_3_0', 'Nuclei_AreaShape_NormalizedMoment_3_2', 'Nuclei_AreaShape_NormalizedMoment_3_3', 'Nuclei_AreaShape_Solidity', 'Nuclei_AreaShape_SpatialMoment_2_1', 'Nuclei_AreaShape_Zernike_1_1', 'Nuclei_AreaShape_Zernike_3_1', 'Nuclei_AreaShape_Zernike_3_3', 'Nuclei_AreaShape_Zernike_4_0', 'Nuclei_AreaShape_Zernike_4_2', 'Nuclei_AreaShape_Zernike_5_1', 'Nuclei_AreaShape_Zernike_5_3', 'Nuclei_AreaShape_Zernike_5_5', 'Nuclei_AreaShape_Zernike_6_0', 'Nuclei_AreaShape_Zernike_6_4', 'Nuclei_AreaShape_Zernike_6_6', 'Nuclei_AreaShape_Zernike_7_1', 'Nuclei_AreaShape_Zernike_7_3', 'Nuclei_AreaShape_Zernike_7_5', 'Nuclei_AreaShape_Zernike_7_7', 'Nuclei_AreaShape_Zernike_8_0', 'Nuclei_AreaShape_Zernike_8_2', 'Nuclei_AreaShape_Zernike_8_4', 'Nuclei_AreaShape_Zernike_8_6', 'Nuclei_AreaShape_Zernike_8_8', 'Nuclei_AreaShape_Zernike_9_1', 'Nuclei_AreaShape_Zernike_9_3', 'Nuclei_AreaShape_Zernike_9_5', 'Nuclei_AreaShape_Zernike_9_7', 'Nuclei_AreaShape_Zernike_9_9', 'Nuclei_Correlation_K_AOGFP_AOPI', 'Nuclei_Correlation_K_AOPI_AOGFP', 'Nuclei_Correlation_Manders_AOGFP_AOPI', 'Nuclei_Correlation_RWC_AOGFP_AOPI', 'Nuclei_Correlation_RWC_AOPI_AOGFP', 'Nuclei_Granularity_10_AOGFP', 'Nuclei_Granularity_10_AOPI', 'Nuclei_Granularity_1_AOGFP', 'Nuclei_Granularity_1_AOPI', 'Nuclei_Granularity_2_AOPI', 'Nuclei_Granularity_3_AOGFP', 'Nuclei_Granularity_3_AOPI', 'Nuclei_Granularity_5_AOPI', 'Nuclei_Granularity_6_AOGFP', 'Nuclei_Granularity_6_AOPI', 'Nuclei_Granularity_7_AOGFP', 'Nuclei_Granularity_8_AOGFP', 'Nuclei_Granularity_8_AOPI', 'Nuclei_Intensity_MaxIntensity_AOPI', 'Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_0_1', 'Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_0_2', 'Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_0_3', 'Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_1_0', 'Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_1_1', 'Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_1_2', 'Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_1_3', 'Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_2_1', 'Nuclei_Mean_Nucleoli_AreaShape_CentralMoment_2_3', 'Nuclei_Mean_Nucleoli_AreaShape_Eccentricity', 'Nuclei_Mean_Nucleoli_AreaShape_EquivalentDiameter', 'Nuclei_Mean_Nucleoli_AreaShape_HuMoment_0', 'Nuclei_Mean_Nucleoli_AreaShape_HuMoment_4', 'Nuclei_Mean_Nucleoli_AreaShape_HuMoment_5', 'Nuclei_Mean_Nucleoli_AreaShape_HuMoment_6', 'Nuclei_Mean_Nucleoli_AreaShape_InertiaTensorEigenvalues_0', 'Nuclei_Mean_Nucleoli_AreaShape_InertiaTensorEigenvalues_1', 'Nuclei_Mean_Nucleoli_AreaShape_InertiaTensor_1_0', 'Nuclei_Mean_Nucleoli_AreaShape_InertiaTensor_1_1', 'Nuclei_Mean_Nucleoli_AreaShape_MaxFeretDiameter', 'Nuclei_Mean_Nucleoli_AreaShape_MeanRadius', 'Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_0_2', 'Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_0_3', 'Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_1_2', 'Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_2_0', 'Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_2_1', 'Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_2_2', 'Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_2_3', 'Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_3_0', 'Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_3_2', 'Nuclei_Mean_Nucleoli_AreaShape_NormalizedMoment_3_3', 'Nuclei_Mean_Nucleoli_AreaShape_Orientation', 'Nuclei_Mean_Nucleoli_AreaShape_SpatialMoment_0_3', 'Nuclei_Mean_Nucleoli_AreaShape_SpatialMoment_2_0', 'Nuclei_Mean_Nucleoli_AreaShape_SpatialMoment_2_2', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_0_0', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_1_1', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_2_0', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_2_2', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_3_1', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_3_3', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_4_0', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_4_2', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_4_4', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_5_1', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_5_3', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_5_5', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_6_0', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_6_2', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_6_4', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_6_6', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_7_1', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_7_3', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_7_5', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_7_7', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_8_0', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_8_2', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_8_4', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_8_6', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_8_8', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_9_1', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_9_3', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_9_5', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_9_7', 'Nuclei_Mean_Nucleoli_AreaShape_Zernike_9_9', 'Nuclei_Mean_Nucleoli_Intensity_StdIntensityEdge_AOPI', 'Nuclei_Texture_Contrast_AOPI_20_03_256', 'Nuclei_Texture_Contrast_AOPI_5_02_256', 'Nuclei_Texture_Correlation_AOGFP_20_02_256', 'Nuclei_Texture_Correlation_AOGFP_5_00_256', 'Nuclei_Texture_Correlation_AOGFP_5_03_256', 'Nuclei_Texture_Correlation_AOPI_10_00_256', 'Nuclei_Texture_Correlation_AOPI_10_01_256', 'Nuclei_Texture_Correlation_AOPI_10_02_256', 'Nuclei_Texture_Correlation_AOPI_10_03_256', 'Nuclei_Texture_Correlation_AOPI_20_00_256', 'Nuclei_Texture_Correlation_AOPI_20_01_256', 'Nuclei_Texture_Correlation_AOPI_20_02_256', 'Nuclei_Texture_Correlation_AOPI_20_03_256', 'Nuclei_Texture_Correlation_AOPI_5_00_256', 'Nuclei_Texture_Correlation_AOPI_5_03_256', 'Nuclei_Texture_DifferenceEntropy_AOPI_20_01_256', 'Nuclei_Texture_InfoMeas1_AOPI_10_00_256', 'Nuclei_Texture_InfoMeas1_AOPI_20_01_256', 'Nuclei_Texture_InfoMeas1_AOPI_20_03_256', 'Nuclei_Texture_InfoMeas1_AOPI_5_00_256', 'Nuclei_Texture_InfoMeas1_AOPI_5_02_256', 'Nuclei_Texture_InfoMeas2_AOPI_20_01_256', 'Nuclei_Texture_InfoMeas2_AOPI_5_02_256', 'Nuclei_Texture_InverseDifferenceMoment_AOPI_20_01_256', 'Nuclei_Texture_InverseDifferenceMoment_AOPI_5_00_256', 'Nuclei_Texture_SumVariance_AOPI_20_01_256', 'Nuclei_Texture_SumVariance_AOPI_20_03_256', 'Cytoplasm_ImageNumber', 'Cytoplasm_AreaShape_CentralMoment_1_0', 'Cytoplasm_AreaShape_CentralMoment_1_2', 'Cytoplasm_AreaShape_CentralMoment_1_3', 'Cytoplasm_AreaShape_CentralMoment_2_3', 'Cytoplasm_AreaShape_Compactness', 'Cytoplasm_AreaShape_Eccentricity', 'Cytoplasm_AreaShape_Extent', 'Cytoplasm_AreaShape_FormFactor', 'Cytoplasm_AreaShape_HuMoment_0', 'Cytoplasm_AreaShape_HuMoment_1', 'Cytoplasm_AreaShape_HuMoment_2', 'Cytoplasm_AreaShape_HuMoment_3', 'Cytoplasm_AreaShape_HuMoment_4', 'Cytoplasm_AreaShape_HuMoment_5', 'Cytoplasm_AreaShape_HuMoment_6', 'Cytoplasm_AreaShape_InertiaTensor_0_0', 'Cytoplasm_AreaShape_InertiaTensor_1_0', 'Cytoplasm_AreaShape_InertiaTensor_1_1', 'Cytoplasm_AreaShape_MinorAxisLength', 'Cytoplasm_AreaShape_NormalizedMoment_0_2', 'Cytoplasm_AreaShape_NormalizedMoment_0_3', 'Cytoplasm_AreaShape_NormalizedMoment_1_2', 'Cytoplasm_AreaShape_NormalizedMoment_1_3', 'Cytoplasm_AreaShape_NormalizedMoment_2_0', 'Cytoplasm_AreaShape_NormalizedMoment_2_1', 'Cytoplasm_AreaShape_NormalizedMoment_2_3', 'Cytoplasm_AreaShape_NormalizedMoment_3_0', 'Cytoplasm_AreaShape_NormalizedMoment_3_1', 'Cytoplasm_AreaShape_NormalizedMoment_3_2', 'Cytoplasm_AreaShape_Orientation', 'Cytoplasm_AreaShape_Zernike_0_0', 'Cytoplasm_AreaShape_Zernike_1_1', 'Cytoplasm_AreaShape_Zernike_2_0', 'Cytoplasm_AreaShape_Zernike_2_2', 'Cytoplasm_AreaShape_Zernike_3_1', 'Cytoplasm_AreaShape_Zernike_3_3', 'Cytoplasm_AreaShape_Zernike_4_0', 'Cytoplasm_AreaShape_Zernike_4_2', 'Cytoplasm_AreaShape_Zernike_5_3', 'Cytoplasm_AreaShape_Zernike_5_5', 'Cytoplasm_AreaShape_Zernike_6_0', 'Cytoplasm_AreaShape_Zernike_6_2', 'Cytoplasm_AreaShape_Zernike_6_4', 'Cytoplasm_AreaShape_Zernike_6_6', 'Cytoplasm_AreaShape_Zernike_7_1', 'Cytoplasm_AreaShape_Zernike_7_3', 'Cytoplasm_AreaShape_Zernike_7_5', 'Cytoplasm_AreaShape_Zernike_7_7', 'Cytoplasm_AreaShape_Zernike_8_0', 'Cytoplasm_AreaShape_Zernike_8_2', 'Cytoplasm_AreaShape_Zernike_8_4', 'Cytoplasm_AreaShape_Zernike_8_6', 'Cytoplasm_AreaShape_Zernike_8_8', 'Cytoplasm_AreaShape_Zernike_9_1', 'Cytoplasm_AreaShape_Zernike_9_3', 'Cytoplasm_AreaShape_Zernike_9_5', 'Cytoplasm_Granularity_10_AOGFP', 'Cytoplasm_Granularity_10_AOPI', 'Cytoplasm_Granularity_1_AOGFP', 'Cytoplasm_Granularity_2_AOGFP', 'Cytoplasm_Granularity_4_AOGFP', 'Cytoplasm_Granularity_5_AOGFP', 'Cytoplasm_Granularity_6_AOGFP', 'Cytoplasm_Granularity_7_AOGFP', 'Cytoplasm_Granularity_7_AOPI', 'Cytoplasm_Granularity_8_AOGFP', 'Cytoplasm_Granularity_8_AOPI', 'Cytoplasm_Granularity_9_AOGFP', 'Cytoplasm_Intensity_MaxIntensityEdge_AOPI', 'Cytoplasm_Intensity_StdIntensityEdge_AOPI', 'Cytoplasm_Texture_Contrast_AOGFP_10_00_256', 'Cytoplasm_Texture_Correlation_AOGFP_10_01_256', 'Cytoplasm_Texture_Correlation_AOGFP_10_02_256', 'Cytoplasm_Texture_Correlation_AOGFP_10_03_256', 'Cytoplasm_Texture_Correlation_AOGFP_20_01_256', 'Cytoplasm_Texture_Correlation_AOGFP_20_02_256', 'Cytoplasm_Texture_Correlation_AOGFP_20_03_256', 'Cytoplasm_Texture_Correlation_AOGFP_5_02_256', 'Cytoplasm_Texture_Correlation_AOPI_10_03_256', 'Cytoplasm_Texture_Correlation_AOPI_20_02_256', 'Cytoplasm_Texture_DifferenceEntropy_AOPI_10_03_256', 'Cytoplasm_Texture_DifferenceEntropy_AOPI_20_01_256', 'Cytoplasm_Texture_DifferenceEntropy_AOPI_20_03_256', 'Cytoplasm_Texture_DifferenceEntropy_AOPI_5_00_256', 'Cytoplasm_Texture_DifferenceEntropy_AOPI_5_01_256', 'Cytoplasm_Texture_DifferenceEntropy_AOPI_5_02_256', 'Cytoplasm_Texture_DifferenceEntropy_AOPI_5_03_256', 'Cytoplasm_Texture_InfoMeas1_AOGFP_10_02_256', 'Cytoplasm_Texture_InfoMeas1_AOGFP_5_01_256', 'Cytoplasm_Texture_InfoMeas1_AOGFP_5_02_256', 'Cytoplasm_Texture_InfoMeas1_AOPI_10_01_256', 'Cytoplasm_Texture_InfoMeas1_AOPI_20_00_256', 'Cytoplasm_Texture_InfoMeas1_AOPI_20_01_256', 'Cytoplasm_Texture_InfoMeas1_AOPI_20_02_256', 'Cytoplasm_Texture_InfoMeas1_AOPI_20_03_256', 'Cytoplasm_Texture_InfoMeas2_AOGFP_5_02_256', 'Cytoplasm_Texture_InfoMeas2_AOPI_10_01_256', 'Cytoplasm_Texture_InfoMeas2_AOPI_20_00_256', 'Cytoplasm_Texture_InfoMeas2_AOPI_20_01_256', 'Cytoplasm_Texture_InfoMeas2_AOPI_20_02_256', 'Cytoplasm_Texture_InfoMeas2_AOPI_20_03_256', 'Cytoplasm_Texture_InfoMeas2_AOPI_5_00_256', 'Cytoplasm_Texture_InfoMeas2_AOPI_5_01_256', 'Cytoplasm_Texture_InverseDifferenceMoment_AOPI_20_01_256', 'Cells_AreaShape_CentralMoment_0_1', 'Cells_AreaShape_CentralMoment_0_3', 'Cells_AreaShape_CentralMoment_1_0', 'Cells_AreaShape_CentralMoment_1_2', 'Cells_AreaShape_CentralMoment_2_0', 'Cells_AreaShape_CentralMoment_2_1', 'Cells_AreaShape_CentralMoment_2_3', 'Cells_AreaShape_Compactness', 'Cells_AreaShape_Eccentricity', 'Cells_AreaShape_Extent', 'Cells_AreaShape_FormFactor', 'Cells_AreaShape_HuMoment_0', 'Cells_AreaShape_HuMoment_2', 'Cells_AreaShape_HuMoment_3', 'Cells_AreaShape_HuMoment_4', 'Cells_AreaShape_HuMoment_5', 'Cells_AreaShape_HuMoment_6', 'Cells_AreaShape_NormalizedMoment_0_2', 'Cells_AreaShape_NormalizedMoment_1_2', 'Cells_AreaShape_NormalizedMoment_2_0', 'Cells_AreaShape_NormalizedMoment_2_1', 'Cells_AreaShape_NormalizedMoment_2_2', 'Cells_AreaShape_NormalizedMoment_2_3', 'Cells_AreaShape_NormalizedMoment_3_0', 'Cells_AreaShape_NormalizedMoment_3_2', 'Cells_AreaShape_Solidity', 'Cells_AreaShape_Zernike_0_0', 'Cells_AreaShape_Zernike_1_1', 'Cells_AreaShape_Zernike_2_2', 'Cells_AreaShape_Zernike_3_1', 'Cells_AreaShape_Zernike_3_3', 'Cells_AreaShape_Zernike_4_0', 'Cells_AreaShape_Zernike_4_2', 'Cells_AreaShape_Zernike_4_4', 'Cells_AreaShape_Zernike_5_1', 'Cells_AreaShape_Zernike_5_3', 'Cells_AreaShape_Zernike_5_5', 'Cells_AreaShape_Zernike_6_0', 'Cells_AreaShape_Zernike_6_2', 'Cells_AreaShape_Zernike_6_4', 'Cells_AreaShape_Zernike_6_6', 'Cells_AreaShape_Zernike_7_1', 'Cells_AreaShape_Zernike_7_3', 'Cells_AreaShape_Zernike_7_5', 'Cells_AreaShape_Zernike_7_7', 'Cells_AreaShape_Zernike_8_0', 'Cells_AreaShape_Zernike_8_2', 'Cells_AreaShape_Zernike_8_4', 'Cells_AreaShape_Zernike_8_6', 'Cells_AreaShape_Zernike_9_1', 'Cells_AreaShape_Zernike_9_3', 'Cells_AreaShape_Zernike_9_5', 'Cells_AreaShape_Zernike_9_7', 'Cells_AreaShape_Zernike_9_9', 'Cells_Granularity_10_AOPI', 'Cells_Granularity_1_AOPI', 'Cells_Granularity_3_AOGFP', 'Cells_Granularity_5_AOPI', 'Cells_Granularity_6_AOGFP', 'Cells_Granularity_6_AOPI', 'Cells_Granularity_7_AOGFP', 'Cells_Granularity_7_AOPI', 'Cells_Granularity_8_AOGFP', 'Cells_Granularity_9_AOGFP', 'Cells_Granularity_9_AOPI', 'Cells_Intensity_MassDisplacement_AOPI', 'Cells_Intensity_MinIntensityEdge_AOGFP', 'Cells_Intensity_StdIntensityEdge_AOGFP', 'Cells_Mean_Vesicles_AreaShape_BoundingBoxMinimum_X', 'Cells_Mean_Vesicles_AreaShape_BoundingBoxMinimum_Y', 'Cells_Mean_Vesicles_AreaShape_CentralMoment_0_1', 'Cells_Mean_Vesicles_AreaShape_CentralMoment_0_3', 'Cells_Mean_Vesicles_AreaShape_CentralMoment_1_1', 'Cells_Mean_Vesicles_AreaShape_CentralMoment_1_2', 'Cells_Mean_Vesicles_AreaShape_CentralMoment_2_1', 'Cells_Mean_Vesicles_AreaShape_CentralMoment_2_3', 'Cells_Mean_Vesicles_AreaShape_Eccentricity', 'Cells_Mean_Vesicles_AreaShape_HuMoment_1', 'Cells_Mean_Vesicles_AreaShape_HuMoment_2', 'Cells_Mean_Vesicles_AreaShape_HuMoment_3', 'Cells_Mean_Vesicles_AreaShape_HuMoment_4', 'Cells_Mean_Vesicles_AreaShape_HuMoment_6', 'Cells_Mean_Vesicles_AreaShape_InertiaTensor_0_1', 'Cells_Mean_Vesicles_AreaShape_NormalizedMoment_0_2', 'Cells_Mean_Vesicles_AreaShape_NormalizedMoment_0_3', 'Cells_Mean_Vesicles_AreaShape_NormalizedMoment_1_2', 'Cells_Mean_Vesicles_AreaShape_NormalizedMoment_2_1', 'Cells_Mean_Vesicles_AreaShape_NormalizedMoment_2_2', 'Cells_Mean_Vesicles_AreaShape_NormalizedMoment_2_3', 'Cells_Mean_Vesicles_AreaShape_NormalizedMoment_3_0', 'Cells_Mean_Vesicles_AreaShape_NormalizedMoment_3_1', 'Cells_Mean_Vesicles_AreaShape_NormalizedMoment_3_2', 'Cells_Mean_Vesicles_AreaShape_Orientation', 'Cells_Mean_Vesicles_AreaShape_Zernike_1_1', 'Cells_Mean_Vesicles_AreaShape_Zernike_3_1', 'Cells_Mean_Vesicles_AreaShape_Zernike_3_3', 'Cells_Mean_Vesicles_AreaShape_Zernike_7_1', 'Cells_Mean_Vesicles_AreaShape_Zernike_8_6', 'Cells_Mean_Vesicles_AreaShape_Zernike_9_1', 'Cells_Mean_Vesicles_AreaShape_Zernike_9_3', 'Cells_Mean_Vesicles_AreaShape_Zernike_9_5', 'Cells_Mean_Vesicles_AreaShape_Zernike_9_9', 'Cells_Mean_Vesicles_Intensity_IntegratedIntensityEdge_AOGFP', 'Cells_Mean_Vesicles_Intensity_IntegratedIntensity_AOGFP', 'Cells_Mean_Vesicles_Intensity_LowerQuartileIntensity_AOPI', 'Cells_Mean_Vesicles_Intensity_MassDisplacement_AOPI', 'Cells_Mean_Vesicles_Intensity_MeanIntensityEdge_AOPI', 'Cells_Mean_Vesicles_Intensity_MeanIntensity_AOPI', 'Cells_Mean_Vesicles_Intensity_MinIntensity_AOPI', 'Cells_Mean_Vesicles_Intensity_StdIntensity_AOGFP', 'Cells_Mean_Vesicles_Number_Object_Number', 'Cells_RadialDistribution_FracAtD_AOGFP_2of4', 'Cells_RadialDistribution_FracAtD_AOGFP_3of4', 'Cells_RadialDistribution_FracAtD_AOPI_2of4', 'Cells_RadialDistribution_MeanFrac_AOGFP_1of4', 'Cells_RadialDistribution_MeanFrac_AOPI_1of4', 'Cells_RadialDistribution_MeanFrac_AOPI_3of4', 'Cells_RadialDistribution_RadialCV_AOGFP_1of4', 'Cells_RadialDistribution_RadialCV_AOGFP_2of4', 'Cells_RadialDistribution_RadialCV_AOGFP_3of4', 'Cells_RadialDistribution_RadialCV_AOGFP_4of4', 'Cells_RadialDistribution_RadialCV_AOPI_4of4', 'Cells_Texture_Contrast_AOPI_20_00_256', 'Cells_Texture_Contrast_AOPI_20_03_256', 'Cells_Texture_Correlation_AOGFP_10_01_256', 'Cells_Texture_Correlation_AOGFP_10_02_256', 'Cells_Texture_Correlation_AOGFP_20_00_256', 'Cells_Texture_Correlation_AOGFP_20_01_256', 'Cells_Texture_Correlation_AOGFP_20_02_256', 'Cells_Texture_Correlation_AOGFP_20_03_256', 'Cells_Texture_Correlation_AOPI_5_00_256', 'Cells_Texture_DifferenceEntropy_AOPI_20_01_256', 'Cells_Texture_DifferenceEntropy_AOPI_5_00_256', 'Cells_Texture_DifferenceEntropy_AOPI_5_02_256', 'Cells_Texture_DifferenceVariance_AOPI_10_00_256', 'Cells_Texture_DifferenceVariance_AOPI_10_01_256', 'Cells_Texture_InfoMeas1_AOGFP_5_01_256', 'Cells_Texture_InfoMeas1_AOPI_10_01_256', 'Cells_Texture_InfoMeas1_AOPI_20_01_256', 'Cells_Texture_InfoMeas1_AOPI_20_02_256', 'Cells_Texture_InfoMeas1_AOPI_20_03_256', 'Cells_Texture_InfoMeas1_AOPI_5_03_256', 'Cells_Texture_InfoMeas2_AOPI_20_03_256', 'Cells_Texture_InfoMeas2_AOPI_5_01_256', 'Cells_Texture_InverseDifferenceMoment_AOPI_20_02_256', 'Cells_Texture_InverseDifferenceMoment_AOPI_20_03_256']

In [178]:
# Encontrar colunas que contenham a palavra 'count'
count_columns = df_selected.filter(like='count').columns

print(f"Colunas que contêm a palavra 'count': {list(count_columns)}")

Colunas que contêm a palavra 'count': ['Nuclei_cell_count']

In [179]:
df_selected = df_selected.drop(columns=['Nuclei_cell_count'])

### 2E) Merge object count

# Export

In [121]:
output_path = eg.diropenbox(msg="Choose an output folder", default=r"D:")
print('Path to save the profile', output_path)

Path to save the profile G:\Meu Drive\Doutorado Thais\Github_Analysis\Dormant_NonDormant\Normalized

In [180]:
output_name = '_'.join(cells_that_run)
df_selected.to_csv(output_path + r'/' + 'dormant_x_nondormant_normalized_negcon_feature_select' + '.csv')
print('Successfully exported to:', output_path + r'/' + output_name + '.csv')

Successfully exported to: G:\Meu Drive\Doutorado Thais\Github_Analysis\Dormant_NonDormant\Normalized/ao_normalized_negcon_feature_select.csv

In [181]:
output_name = '_'.join(cells_that_run)
df_norm2.to_csv(output_path + r'/' + 'dormant_x_nondormant_normalized_negcon' + '.csv')
print('Successfully exported to:', output_path + r'/' + output_name + '.csv')

Successfully exported to: G:\Meu Drive\Doutorado Thais\Github_Analysis\Dormant_NonDormant\Normalized/ao_normalized_negcon_feature_select.csv